// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByI5gasmd34EKo3Rz2E0OLDMOmvbIOqn0',
    appId: '1:1038672515920:web:a5767c226e2d29f6ced255',
    messagingSenderId: '1038672515920',
    projectId: 'cloudnotifications-233b8',
    authDomain: 'cloudnotifications-233b8.firebaseapp.com',
    databaseURL: 'https://cloudnotifications-233b8.firebaseio.com',
    storageBucket: 'cloudnotifications-233b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCexTx-qZ6lG8jb3g9mLLJ6e9rzVh15GZc',
    appId: '1:1038672515920:android:cc59fd1e95decaf7ced255',
    messagingSenderId: '1038672515920',
    projectId: 'cloudnotifications-233b8',
    databaseURL: 'https://cloudnotifications-233b8.firebaseio.com',
    storageBucket: 'cloudnotifications-233b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvjbmNQ8eeiGDCKAfIBOnzgjOgNxJhyzQ',
    appId: '1:1038672515920:ios:ca59a30192fee155ced255',
    messagingSenderId: '1038672515920',
    projectId: 'cloudnotifications-233b8',
    databaseURL: 'https://cloudnotifications-233b8.firebaseio.com',
    storageBucket: 'cloudnotifications-233b8.appspot.com',
    androidClientId: '1038672515920-4596civfasputagdret03j9h5v5vfnt4.apps.googleusercontent.com',
    iosClientId: '1038672515920-1d9g8m1dcjjml94c6uu6r16elcoennqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvjbmNQ8eeiGDCKAfIBOnzgjOgNxJhyzQ',
    appId: '1:1038672515920:ios:ca59a30192fee155ced255',
    messagingSenderId: '1038672515920',
    projectId: 'cloudnotifications-233b8',
    databaseURL: 'https://cloudnotifications-233b8.firebaseio.com',
    storageBucket: 'cloudnotifications-233b8.appspot.com',
    androidClientId: '1038672515920-4596civfasputagdret03j9h5v5vfnt4.apps.googleusercontent.com',
    iosClientId: '1038672515920-1d9g8m1dcjjml94c6uu6r16elcoennqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseapp',
  );
}
